# This file acts as the base configuration file for the project.
# See configs/template.yaml for an example how to create a deviating configuration file
# By default the config/user.yaml configuration file is used.

# project metadata
project_name: "iphone-segmentation"
note: "openmask3d"

# legacy fields kept for compatibility with existing modules
robot_parameters:
  verbose: False

# device used by Open3D importer
device: "cuda"

pre_scanned_graphs:
  base_fiducial_id: 52
  graph_frame_name_prefix: "filtered_fiducial_"
  floor: -0.1
  low_res: ""  # optional when aligning against a Spot autowalk
  high_res: "my_desk"
  masked: ""

# paths are relative from project_root_directory
subpaths:
  cache: "cache/"
  logs: "data/logs/"
  output: "output/"
  resume_from: "path/to/weights"
  data: "data/"
  graphs: "data/graphs/"
  prescans: "data/prescans"
  autowalks: "data/autowalk"
  point_clouds: "data/point_clouds"
  aligned_point_clouds: "data/aligned_point_clouds"
  masks: "data/masked"
  # environment
  environment: ".environment.yaml"
  spot_description: "spot_description"
  tmp: "data/tmp"
  openmask_features: "data/openmask_features"

servers:
  openmask:
    ip: "127.0.0.1"
    port: 5001
    route: "openmask/save_and_predict"
